import JSPProblem.HujterTuza
import JSPProblem.LinkTriangleFree
import JSPProblem.FingerprintBuild

/-!
# JSP-000728 — the link graph on a sum-free ground set

The dual of `LinkTriangleFree.lean`: instead of pushing the ground set into
the upper half `(n/2, ∞)` to kill the sum edges of the link graph, we let the
ground set `A` itself be **sum-free**.  For `S ⊆ A` and `x, y ∈ A`:

* `x + y ∉ S` (sums leave `A`), so every link edge inside `A` is a
  *difference* edge (`linkAdj_iff_diff_of_isSumFree`);
* no `x ∈ A` carries a loop — each of the three loop shapes exhibits a Schur
  triple inside `A` (`not_linkLoop_of_isSumFree`);
* no triangle: for `x < y < z` in `A`, pairwise adjacency forces
  `y − x, z − y, z − x ∈ S ⊆ A`, and `(y − x) + (z − y) = z − x` is a Schur
  triple inside `A` (`triangleFree_linkAdj_of_isSumFree`).

Hence `L_S[A]` is a **loopless triangle-free** graph for *every* `S ⊆ A` —
no size restriction on `S`, no `n/2` threshold — and Hujter–Tuza gives

  `|linkMaxSets S A| ≤ 2^{|A|/2} ≤ 2^{(n+1)/4}`

(`card_linkMaxSets_le_two_rpow_of_isSumFree_ground`,
`card_linkMaxSets_le_two_rpow_quarter`): the per-fingerprint bound at the
BLST `1/4` scale, using `2·|A| ≤ n + 1` for `A ⊆ [1, n]` sum-free
(`two_mul_card_le_of_isSumFree`).

## The glue layer

For a container `C = A ∪ B` with `A ⊆ [1, n]` sum-free and `M ⊆ C`
inclusion-maximal sum-free:

* `M ∩ A` is link-independent w.r.t. every `T ⊆ M`
  (`linkIndepSet_inter_of_isSumFree`);
* `M ∩ A` is a **maximal** link-independent subset of `A` for the link
  graph `L_{M ∩ B}` (`linkMaxIndepSet_inter_of_isMaxSumFree`): every
  obstruction of an `x ∈ A ∖ M` either has both witnesses in `A` —
  contradicting `IsSumFree A` — or lands a loop/edge generated by the
  `B`-fingerprint.  This gives the sigma-count
  `#{M ⊆ A ∪ B} ≤ Σ_{S ⊆ B} |linkMaxSets S A|`
  (`card_maxSumFreeSets_filter_union_le_sum_linkMaxSets`) and the
  unconditional Moon–Moser form `≤ 2^{|B|} · 3^{|A|/3}`.

The determination gap: the summands `|linkMaxSets S A|` are bounded by
`2^{|A|/2}` only when `L_S[A]` is triangle-free, which we can prove for
`S ⊆ A` but not for a general `S ⊆ B`.  This remaining hypothesis is
packaged as `SumFreeMISBound A B`; under it the container count is
`≤ 2^{|B|} · 2^{(n+1)/4}`
(`card_maxSumFreeSets_filter_union_le_two_pow_quarter`).
-/

namespace JSP000728

/-! ## Difference edges, no loops, no triangles on a sum-free ground -/

/-- **Only difference edges inside `A`.**  For `A` sum-free, `S ⊆ A` and
`x, y ∈ A`, the sum edge `x + y ∈ S` is impossible (`x + y ∉ A ∋ S`), so
link adjacency collapses to the two difference orientations. -/
theorem linkAdj_iff_diff_of_isSumFree {S A : Finset ℤ} {x y : ℤ}
    (hSA : S ⊆ A) (hA : IsSumFree A) (hx : x ∈ A) (hy : y ∈ A) :
    linkAdj S x y ↔ x - y ∈ S ∨ y - x ∈ S := by
  constructor
  · rintro (h | h | h)
    · exact absurd (hSA h) (hA x hx y hy)
    · exact Or.inl h
    · exact Or.inr h
  · rintro (h | h)
    · exact Or.inr (Or.inl h)
    · exact Or.inr (Or.inr h)

/-- **Ordered form.**  For `x < y` in a positive sum-free `A`, the edge
`x ~ y` is witnessed by the positive difference `y − x ∈ S`; the
negatively-oriented `x − y < 0` lies below every element of `A ∋ S`. -/
theorem linkAdj_iff_sub_of_lt_of_isSumFree {S A : Finset ℤ} {x y : ℤ}
    (hSA : S ⊆ A) (hA : IsSumFree A) (hpos : ∀ a ∈ A, 1 ≤ a)
    (hx : x ∈ A) (hy : y ∈ A) (hxy : x < y) :
    linkAdj S x y ↔ y - x ∈ S := by
  rw [linkAdj_iff_diff_of_isSumFree hSA hA hx hy]
  constructor
  · rintro (h | h)
    · have h1 := hpos _ (hSA h)
      omega
    · exact h
  · exact fun h => Or.inr h

/-- **No loops on `A`.**  For `x ∈ A`, `S ⊆ A`, `A` sum-free: a loop at `x`
would be a Schur triple inside `A` — `z + (x − z) = x` with
`z, x − z ∈ A`, or `x + z ∈ A`, or `x + x ∈ A`. -/
theorem not_linkLoop_of_isSumFree {S A : Finset ℤ} {x : ℤ}
    (hSA : S ⊆ A) (hA : IsSumFree A) (hx : x ∈ A) :
    ¬ linkLoop S x := by
  rintro (⟨z, hz, hxz⟩ | ⟨z, hz, hxz⟩ | hxx)
  · have e : z + (x - z) = x := by ring
    have hmem : z + (x - z) ∈ A := by rw [e]; exact hx
    exact hA z (hSA hz) (x - z) (hSA hxz) hmem
  · exact hA x hx z (hSA hz) (hSA hxz)
  · exact hA x hx x hx (hSA hxx)

/-- **Ordered triangle case.**  For `x < y < z` in a positive sum-free `A`,
the three edges are the positive differences `y − x, z − y, z − x ∈ S ⊆ A`,
and `(y − x) + (z − y) = z − x` is a Schur triple inside `A`. -/
theorem linkAdj_not_triangle_ordered_of_isSumFree_ground {S A : Finset ℤ}
    {x y z : ℤ}
    (hSA : S ⊆ A) (hA : IsSumFree A) (hpos : ∀ a ∈ A, 1 ≤ a)
    (hx : x ∈ A) (hy : y ∈ A) (hz : z ∈ A)
    (hxy : x < y) (hyz : y < z) :
    ¬ (linkAdj S x y ∧ linkAdj S y z ∧ linkAdj S x z) := by
  rintro ⟨hxyL, hyzL, hxzL⟩
  have dxy : y - x ∈ S :=
    (linkAdj_iff_sub_of_lt_of_isSumFree hSA hA hpos hx hy hxy).mp hxyL
  have dyz : z - y ∈ S :=
    (linkAdj_iff_sub_of_lt_of_isSumFree hSA hA hpos hy hz hyz).mp hyzL
  have dxz : z - x ∈ S :=
    (linkAdj_iff_sub_of_lt_of_isSumFree hSA hA hpos hx hz
      (hxy.trans hyz)).mp hxzL
  have e : y - x + (z - y) = z - x := by ring
  have hmem : y - x + (z - y) ∈ A := by rw [e]; exact hSA dxz
  exact hA (y - x) (hSA dxy) (z - y) (hSA dyz) hmem

/-- **No triangles on a sum-free ground.**  Three pairwise distinct
elements of `A` never form a link triangle for `S ⊆ A`; the six orderings
reduce to the ordered case via `linkAdj_comm`. -/
theorem linkAdj_not_triangle_of_isSumFree_ground {S A : Finset ℤ} {x y z : ℤ}
    (hSA : S ⊆ A) (hA : IsSumFree A) (hpos : ∀ a ∈ A, 1 ≤ a)
    (hx : x ∈ A) (hy : y ∈ A) (hz : z ∈ A)
    (hxy : x ≠ y) (hyz : y ≠ z) (hxz : x ≠ z) :
    ¬ (linkAdj S x y ∧ linkAdj S y z ∧ linkAdj S x z) := by
  rcases lt_or_gt_of_ne hxy with hxy' | hxy'
  · rcases lt_or_gt_of_ne hyz with hyz' | hyz'
    · -- x < y < z
      exact linkAdj_not_triangle_ordered_of_isSumFree_ground
        hSA hA hpos hx hy hz hxy' hyz'
    · rcases lt_or_gt_of_ne hxz with hxz' | hxz'
      · -- x < z < y
        exact fun h =>
          linkAdj_not_triangle_ordered_of_isSumFree_ground
            hSA hA hpos hx hz hy hxz' hyz'
            ⟨h.2.2, linkAdj_comm.mp h.2.1, h.1⟩
      · -- z < x < y
        exact fun h =>
          linkAdj_not_triangle_ordered_of_isSumFree_ground
            hSA hA hpos hz hx hy hxz' hxy'
            ⟨linkAdj_comm.mp h.2.2, h.1, linkAdj_comm.mp h.2.1⟩
  · rcases lt_or_gt_of_ne hyz with hyz' | hyz'
    · rcases lt_or_gt_of_ne hxz with hxz' | hxz'
      · -- y < x < z
        exact fun h =>
          linkAdj_not_triangle_ordered_of_isSumFree_ground
            hSA hA hpos hy hx hz hxy' hxz'
            ⟨linkAdj_comm.mp h.1, h.2.2, h.2.1⟩
      · -- y < z < x
        exact fun h =>
          linkAdj_not_triangle_ordered_of_isSumFree_ground
            hSA hA hpos hy hz hx hyz' hxz'
            ⟨h.2.1, linkAdj_comm.mp h.2.2, linkAdj_comm.mp h.1⟩
    · -- z < y < x
      exact fun h =>
        linkAdj_not_triangle_ordered_of_isSumFree_ground
          hSA hA hpos hz hy hx hyz' hxy'
          ⟨linkAdj_comm.mp h.2.1, linkAdj_comm.mp h.1,
            linkAdj_comm.mp h.2.2⟩

/-- **Packaged form: `L_S[A]` is triangle-free** whenever `S ⊆ A` and `A` is
a positive sum-free set.  No size restriction on `S` or `A` is needed. -/
theorem triangleFree_linkAdj_of_isSumFree {S A : Finset ℤ}
    (hSA : S ⊆ A) (hA : IsSumFree A) (hpos : ∀ a ∈ A, 1 ≤ a) :
    triangleFree (linkAdj S) A :=
  fun _x hx _y hy _z hz hxy hyz hxz =>
    linkAdj_not_triangle_of_isSumFree_ground hSA hA hpos hx hy hz
      hxy hyz hxz

/-- **Neighbourhoods are independent** on a sum-free ground: two distinct
link-neighbours `v, w` of a common vertex `u ∈ A` are never adjacent — an
immediate consequence of triangle-freeness. -/
theorem linkAdj_not_adj_of_common_neighbour_of_isSumFree_ground
    {S A : Finset ℤ} {u v w : ℤ}
    (hSA : S ⊆ A) (hA : IsSumFree A) (hpos : ∀ a ∈ A, 1 ≤ a)
    (hu : u ∈ A) (hv : v ∈ A) (hw : w ∈ A)
    (huv : u ≠ v) (hvw : v ≠ w) (huw : u ≠ w)
    (h1 : linkAdj S u v) (h2 : linkAdj S u w) : ¬ linkAdj S v w :=
  fun h3 =>
    linkAdj_not_triangle_of_isSumFree_ground hSA hA hpos hu hv hw
      huv hvw huw ⟨h1, h3, h2⟩

/-- **Every subset of `A` is link-independent** w.r.t. every `S ⊆ A`, so
`linkSets S A` is the full powerset.  The saving therefore lives entirely
in the *maximality* constraint counted by `linkMaxSets`. -/
theorem linkSets_eq_powerset_of_isSumFree_ground {S A : Finset ℤ}
    (hSA : S ⊆ A) (hA : IsSumFree A) : linkSets S A = A.powerset := by
  rw [linkSets]
  exact Finset.filter_true_of_mem fun t ht =>
    linkIndepSet_of_isSumFree hA hSA (Finset.mem_powerset.mp ht)

/-! ## The Hujter–Tuza bound on a sum-free ground -/

/-- **Hujter–Tuza on a sum-free ground**: for `A` positive sum-free and
`S ⊆ A`, the link graph `L_S[A]` is triangle-free (and loopless), so the
number of maximal link-independent subsets of `A` is at most `2^{|A|/2}`. -/
theorem card_linkMaxSets_le_two_rpow_of_isSumFree_ground {S A : Finset ℤ}
    (hSA : S ⊆ A) (hA : IsSumFree A) (hpos : ∀ a ∈ A, 1 ≤ a) :
    ((linkMaxSets S A).card : ℝ) ≤ (2 : ℝ) ^ ((A.card : ℝ) / 2) := by
  have hTF : triangleFree (linkAdj S) A :=
    triangleFree_linkAdj_of_isSumFree hSA hA hpos
  have h := misCount_le_two_rpow_of_triangleFree (linkAdj S) (linkLoop S)
    (fun x y h => linkAdj_comm.mp h) A.card A le_rfl hTF
  simp only [misCount, maxIndepSets_link] at h
  exact h

/-- **The `1/4` scale.**  For `A ⊆ {1,…,n}` sum-free we have
`2·|A| ≤ n + 1` (`two_mul_card_le_of_isSumFree`), hence
`|linkMaxSets S A| ≤ 2^{|A|/2} ≤ 2^{(n+1)/4}` for every `S ⊆ A`. -/
theorem card_linkMaxSets_le_two_rpow_quarter {S A : Finset ℤ} {n : ℕ}
    (hSA : S ⊆ A) (hAI : A ⊆ interval n) (hA : IsSumFree A) :
    ((linkMaxSets S A).card : ℝ) ≤ (2 : ℝ) ^ (((n : ℝ) + 1) / 4) := by
  have hpos : ∀ a ∈ A, 1 ≤ a :=
    fun a ha => (Finset.mem_Icc.mp (hAI ha)).1
  have h1 := card_linkMaxSets_le_two_rpow_of_isSumFree_ground hSA hA hpos
  have hcard : 2 * A.card ≤ n + 1 := two_mul_card_le_of_isSumFree hAI hA
  have h2 : (A.card : ℝ) ≤ ((n : ℝ) + 1) / 2 := by
    have h3 : (2 * A.card : ℝ) ≤ (n : ℝ) + 1 := by exact_mod_cast hcard
    linarith
  refine h1.trans (Real.rpow_le_rpow_of_exponent_le
    (by norm_num : (1 : ℝ) ≤ 2) ?_)
  linarith

/-! ## The glue layer -/

/-- **Trace independence.**  Inside a sum-free `M`, the trace `M ∩ A` is
link-independent w.r.t. every `T ⊆ M` — in particular w.r.t. `M ∩ A` and
`M ∩ B`.  This is just `linkIndepSet_of_isSumFree` instantiated at
`t = M ∩ A`. -/
theorem linkIndepSet_inter_of_isSumFree {M A T : Finset ℤ}
    (hM : IsSumFree M) (hT : T ⊆ M) : linkIndepSet T (M ∩ A) :=
  linkIndepSet_of_isSumFree hM hT Finset.inter_subset_left

/-- **Trace independence w.r.t. sub-fingerprints of itself.** -/
theorem linkIndepSet_inter_self {M A T : Finset ℤ}
    (hM : IsSumFree M) (hT : T ⊆ M ∩ A) : linkIndepSet T (M ∩ A) :=
  linkIndepSet_inter_of_isSumFree hM (hT.trans Finset.inter_subset_left)

/-- **Maximality transfer onto a sum-free ground.**  Let `A ⊆ {1,…,n}` be
sum-free and `M ⊆ A ∪ B` an inclusion-maximal sum-free subset of
`{1,…,n}`.  Then `M ∩ A` is a *maximal* link-independent subset of `A` for
the link graph generated by the `B`-fingerprint `M ∩ B`.

For `x ∈ A ∖ M` the maximality obstruction decomposes over `M = (M ∩ A) ∪
(M ∩ B)`: whenever both witnesses lie in `M ∩ A ⊆ A` the obstruction is a
Schur triple inside `A` — impossible — and every mixed or `B`-side
obstruction is a loop or an edge into `M ∩ A`.  Note the fingerprint is
`M ∩ B`, *not* a subset of `A`: triangle-freeness of `L_{M ∩ B}[A]` is not
covered by `triangleFree_linkAdj_of_isSumFree`. -/
theorem linkMaxIndepSet_inter_of_isMaxSumFree {n : ℕ} {M A B : Finset ℤ}
    (hM : IsMaxSumFree n M) (hAI : A ⊆ interval n) (hAsf : IsSumFree A)
    (hcover : M ⊆ A ∪ B) :
    linkMaxIndepSet (M ∩ B) A (M ∩ A) := by
  refine ⟨Finset.inter_subset_right,
    linkIndepSet_of_isSumFree hM.2.1 Finset.inter_subset_left
      Finset.inter_subset_left, ?_⟩
  intro x hxA hxt
  have hxM : x ∉ M := fun h => hxt (Finset.mem_inter.mpr ⟨h, hxA⟩)
  have hd : ∀ a ∈ M, a ∈ M ∩ A ∨ a ∈ M ∩ B := by
    intro a ha
    rcases Finset.mem_union.mp (hcover ha) with h | h
    · exact Or.inl (Finset.mem_inter.mpr ⟨ha, h⟩)
    · exact Or.inr (Finset.mem_inter.mpr ⟨ha, h⟩)
  rcases hM.exists_obstruction (hAI hxA) hxM with hsum | hax | hxa | hxx
  · obtain ⟨a, ha, b, hb, hab⟩ := hsum
    rcases hd a ha with haA | haB <;> rcases hd b hb with hbA | hbB
    · -- `a, b ∈ A`, `a + b = x ∈ A`: Schur triple inside `A`.
      have hmem : a + b ∈ A := by rw [hab]; exact hxA
      exact absurd hmem
        (hAsf a (Finset.mem_inter.mp haA).2 b (Finset.mem_inter.mp hbA).2)
    · -- `a ∈ A`, `b ∈ B`: edge `x ~ a` via `x − a = b ∈ M ∩ B`.
      refine Or.inr ⟨a, haA, Or.inr (Or.inl ?_)⟩
      have e : x - a = b := by omega
      rwa [e]
    · -- `a ∈ B`, `b ∈ A`: edge `x ~ b` via `x − b = a ∈ M ∩ B`.
      refine Or.inr ⟨b, hbA, Or.inr (Or.inl ?_)⟩
      have e : x - b = a := by omega
      rwa [e]
    · -- `a, b ∈ B`: loop at `x` via `x − a = b`.
      refine Or.inl (Or.inl ⟨a, haB, ?_⟩)
      have e : x - a = b := by omega
      rwa [e]
  · obtain ⟨a, ha, hax⟩ := hax
    rcases hd a ha with haA | haB <;> rcases hd (a + x) hax with haxA | haxB
    · -- `a, a + x ∈ A`: `x + a = a + x ∈ A` contradicts `IsSumFree A`.
      exact absurd (Finset.mem_inter.mp haxA).2
        (hAsf a (Finset.mem_inter.mp haA).2 x hxA)
    · -- `a ∈ A`, `a + x ∈ B`: edge `x ~ a` via `x + a ∈ M ∩ B`.
      refine Or.inr ⟨a, haA, Or.inl ?_⟩
      rwa [add_comm x a]
    · -- `a ∈ B`, `a + x ∈ A`: edge `x ~ a + x` via `(a + x) − x = a`.
      refine Or.inr ⟨a + x, haxA, Or.inr (Or.inr ?_)⟩
      have e : a + x - x = a := by ring
      rwa [e]
    · -- `a, a + x ∈ B`: loop at `x` via `x + a ∈ M ∩ B`.
      refine Or.inl (Or.inr (Or.inl ⟨a, haB, ?_⟩))
      rwa [add_comm x a]
  · obtain ⟨a, ha, hxa⟩ := hxa
    rcases hd a ha with haA | haB <;> rcases hd (x + a) hxa with hxaA | hxaB
    · -- `a, x + a ∈ A`: Schur triple inside `A`.
      exact absurd (Finset.mem_inter.mp hxaA).2
        (hAsf x hxA a (Finset.mem_inter.mp haA).2)
    · -- `a ∈ A`, `x + a ∈ B`: edge `x ~ a` via `x + a ∈ M ∩ B`.
      exact Or.inr ⟨a, haA, Or.inl hxaB⟩
    · -- `a ∈ B`, `x + a ∈ A`: edge `x ~ x + a` via `(x + a) − x = a`.
      refine Or.inr ⟨x + a, hxaA, Or.inr (Or.inr ?_)⟩
      have e : x + a - x = a := by ring
      rwa [e]
    · -- `a, x + a ∈ B`: loop at `x` via `x + a ∈ M ∩ B`.
      exact Or.inl (Or.inr (Or.inl ⟨a, haB, hxaB⟩))
  · -- `x + x ∈ M`: inside `A` it is a Schur triple; inside `B` a loop.
    rcases hd (x + x) hxx with hxxA | hxxB
    · exact absurd (Finset.mem_inter.mp hxxA).2 (hAsf x hxA x hxA)
    · exact Or.inl (Or.inr (Or.inr hxxB))

/-- Membership form: the `A`-trace lies in `linkMaxSets (M ∩ B) A`. -/
theorem mem_linkMaxSets_inter_of_isMaxSumFree {n : ℕ} {M A B : Finset ℤ}
    (hM : IsMaxSumFree n M) (hAI : A ⊆ interval n) (hAsf : IsSumFree A)
    (hcover : M ⊆ A ∪ B) :
    M ∩ A ∈ linkMaxSets (M ∩ B) A :=
  mem_linkMaxSets.mpr ⟨Finset.inter_subset_right,
    linkMaxIndepSet_inter_of_isMaxSumFree hM hAI hAsf hcover⟩

/-- **Counting through the `B`-fingerprint/`A`-trace sigma.**  For
`A ⊆ {1,…,n}` sum-free, the map `M ↦ (M ∩ B, M ∩ A)` injects the maximal
sum-free sets housed by `A ∪ B` into pairs `(S, t)` with `S ⊆ B` and
`t ∈ linkMaxSets S A`:
`#{M ∈ maxSumFreeSets n : M ⊆ A ∪ B} ≤ Σ_{S ⊆ B} |linkMaxSets S A|`. -/
theorem card_maxSumFreeSets_filter_union_le_sum_linkMaxSets {n : ℕ}
    {A B : Finset ℤ}
    (hAI : A ⊆ interval n) (hAsf : IsSumFree A) :
    ((maxSumFreeSets n).filter (· ⊆ A ∪ B)).card ≤
      ∑ S ∈ B.powerset, (linkMaxSets S A).card := by
  classical
  have him : ∀ M ∈ (maxSumFreeSets n).filter (· ⊆ A ∪ B),
      (⟨M ∩ B, M ∩ A⟩ : Σ _ : Finset ℤ, Finset ℤ) ∈
        B.powerset.sigma fun S => linkMaxSets S A := by
    intro M hM
    obtain ⟨hMmem, hMC⟩ := Finset.mem_filter.mp hM
    have hMmax := mem_maxSumFreeSets.mp hMmem
    rw [Finset.mem_sigma]
    refine ⟨Finset.mem_powerset.mpr Finset.inter_subset_right, ?_⟩
    rw [mem_linkMaxSets]
    exact ⟨Finset.inter_subset_right,
      linkMaxIndepSet_inter_of_isMaxSumFree hMmax hAI hAsf hMC⟩
  have hinj : Set.InjOn
      (fun M : Finset ℤ => (⟨M ∩ B, M ∩ A⟩ : Σ _ : Finset ℤ, Finset ℤ))
      ↑((maxSumFreeSets n).filter (· ⊆ A ∪ B)) := by
    intro M hM M' hM' heq
    obtain ⟨-, hMC⟩ := Finset.mem_filter.mp (Finset.mem_coe.mp hM)
    obtain ⟨-, hM'C⟩ := Finset.mem_filter.mp (Finset.mem_coe.mp hM')
    have h1 : M ∩ B = M' ∩ B := congrArg Sigma.fst heq
    have h2 : M ∩ A = M' ∩ A := congrArg Sigma.snd heq
    have e : M ∩ A ∪ M ∩ B = M := by
      ext y
      simp only [Finset.mem_union, Finset.mem_inter]
      constructor
      · rintro (⟨hy, -⟩ | ⟨hy, -⟩) <;> exact hy
      · intro hy
        rcases Finset.mem_union.mp (hMC hy) with h | h
        · exact Or.inl ⟨hy, h⟩
        · exact Or.inr ⟨hy, h⟩
    have e' : M' ∩ A ∪ M' ∩ B = M' := by
      ext y
      simp only [Finset.mem_union, Finset.mem_inter]
      constructor
      · rintro (⟨hy, -⟩ | ⟨hy, -⟩) <;> exact hy
      · intro hy
        rcases Finset.mem_union.mp (hM'C hy) with h | h
        · exact Or.inl ⟨hy, h⟩
        · exact Or.inr ⟨hy, h⟩
    calc M = M ∩ A ∪ M ∩ B := e.symm
      _ = M' ∩ A ∪ M' ∩ B := by rw [h1, h2]
      _ = M' := e'
  calc ((maxSumFreeSets n).filter (· ⊆ A ∪ B)).card
      ≤ (B.powerset.sigma fun S => linkMaxSets S A).card :=
        Finset.card_le_card_of_injOn _ him hinj
    _ = ∑ S ∈ B.powerset, (linkMaxSets S A).card := Finset.card_sigma _ _

/-- **Unconditional assembled bound.**  Each summand is bounded by the
Moon–Moser `3^{|A|/3}` (no triangle-freeness is available for fingerprints
`S ⊆ B ∖ A`), giving `#{M ⊆ A ∪ B} ≤ 2^{|B|} · 3^{|A|/3}`. -/
theorem card_maxSumFreeSets_filter_union_le_two_pow_mul_three_rpow {n : ℕ}
    {A B : Finset ℤ}
    (hAI : A ⊆ interval n) (hAsf : IsSumFree A) :
    (((maxSumFreeSets n).filter (· ⊆ A ∪ B)).card : ℝ) ≤
      2 ^ B.card * (3 : ℝ) ^ ((A.card : ℝ) / 3) := by
  have hsum := card_maxSumFreeSets_filter_union_le_sum_linkMaxSets
    (B := B) hAI hAsf
  have hreal : (((maxSumFreeSets n).filter (· ⊆ A ∪ B)).card : ℝ) ≤
      ∑ S ∈ B.powerset, ((linkMaxSets S A).card : ℝ) := by
    exact_mod_cast hsum
  calc (((maxSumFreeSets n).filter (· ⊆ A ∪ B)).card : ℝ)
      ≤ ∑ S ∈ B.powerset, ((linkMaxSets S A).card : ℝ) := hreal
    _ ≤ ∑ _S ∈ B.powerset, (3 : ℝ) ^ ((A.card : ℝ) / 3) :=
        Finset.sum_le_sum fun S _ => card_linkMaxSets_le_three_rpow S A
    _ = (B.powerset.card : ℝ) * (3 : ℝ) ^ ((A.card : ℝ) / 3) := by
        rw [Finset.sum_const, nsmul_eq_mul]
    _ = 2 ^ B.card * (3 : ℝ) ^ ((A.card : ℝ) / 3) := by
        rw [Finset.card_powerset]
        push_cast
        ring

/-- **Unconditional bound at fixed scale.**  Since `2·|A| ≤ n + 1`,
`|A|/3 ≤ (n+1)/6`, so `#{M ⊆ A ∪ B} ≤ 2^{|B|} · 3^{(n+1)/6}`. -/
theorem card_maxSumFreeSets_filter_union_le_two_pow_mul_three_rpow_quarter
    {n : ℕ} {A B : Finset ℤ}
    (hAI : A ⊆ interval n) (hAsf : IsSumFree A) :
    (((maxSumFreeSets n).filter (· ⊆ A ∪ B)).card : ℝ) ≤
      2 ^ B.card * (3 : ℝ) ^ (((n : ℝ) + 1) / 6) := by
  refine (card_maxSumFreeSets_filter_union_le_two_pow_mul_three_rpow hAI
    hAsf).trans ?_
  refine mul_le_mul_of_nonneg_left ?_ (pow_nonneg (by norm_num) _)
  refine Real.rpow_le_rpow_of_exponent_le (by norm_num : (1 : ℝ) ≤ 3) ?_
  have hcard : 2 * A.card ≤ n + 1 := two_mul_card_le_of_isSumFree hAI hAsf
  have h2 : (A.card : ℝ) ≤ ((n : ℝ) + 1) / 2 := by
    have h3 : (2 * A.card : ℝ) ≤ (n : ℝ) + 1 := by exact_mod_cast hcard
    linarith
  linarith

/-! ## The determination gap -/

/-- **Determining-fingerprint hypothesis** for a sum-free ground `A`:
every fingerprint `S ⊆ B` has at most `2^{|A|/2}` maximal link-independent
subsets of `A`.  This is the missing ingredient for the `2^{|B|} · 2^{n/4}`
container bound: it is equivalent to the Hujter–Tuza bound being available
for `L_S[A]` for all `S ⊆ B`, which holds when every such `S` lies in `A`
(triangle-freeness, `triangleFree_linkAdj_of_isSumFree`) but can fail for
`S ⊆ B ∖ A` — sum edges `x + y ∈ S` may then close triangles. -/
def SumFreeMISBound (A B : Finset ℤ) : Prop :=
  ∀ S ⊆ B, ((linkMaxSets S A).card : ℝ) ≤ (2 : ℝ) ^ ((A.card : ℝ) / 2)

/-- The hypothesis is satisfied when `B ⊆ A` (every fingerprint is a subset
of the sum-free ground, so `L_S[A]` is triangle-free).  In particular
`SumFreeMISBound A A` always holds for positive sum-free `A`. -/
theorem determiningFingerprint_of_subset {A B : Finset ℤ} (hBA : B ⊆ A)
    (hA : IsSumFree A) (hpos : ∀ a ∈ A, 1 ≤ a) :
    SumFreeMISBound A B :=
  fun _S hSB =>
    card_linkMaxSets_le_two_rpow_of_isSumFree_ground (hSB.trans hBA) hA hpos

/-- **Conditional `1/4`-scale container bound.**  Under
`SumFreeMISBound A B`, the maximal sum-free sets housed by `A ∪ B`
number at most `2^{|B|} · 2^{|A|/2}`. -/
theorem card_maxSumFreeSets_filter_union_le_two_pow_mul_two_rpow {n : ℕ}
    {A B : Finset ℤ}
    (hAI : A ⊆ interval n) (hAsf : IsSumFree A)
    (hDet : SumFreeMISBound A B) :
    (((maxSumFreeSets n).filter (· ⊆ A ∪ B)).card : ℝ) ≤
      2 ^ B.card * (2 : ℝ) ^ ((A.card : ℝ) / 2) := by
  have hsum := card_maxSumFreeSets_filter_union_le_sum_linkMaxSets
    (B := B) hAI hAsf
  have hreal : (((maxSumFreeSets n).filter (· ⊆ A ∪ B)).card : ℝ) ≤
      ∑ S ∈ B.powerset, ((linkMaxSets S A).card : ℝ) := by
    exact_mod_cast hsum
  calc (((maxSumFreeSets n).filter (· ⊆ A ∪ B)).card : ℝ)
      ≤ ∑ S ∈ B.powerset, ((linkMaxSets S A).card : ℝ) := hreal
    _ ≤ ∑ S ∈ B.powerset, (2 : ℝ) ^ ((A.card : ℝ) / 2) :=
        Finset.sum_le_sum fun S hS => hDet S (Finset.mem_powerset.mp hS)
    _ = (B.powerset.card : ℝ) * (2 : ℝ) ^ ((A.card : ℝ) / 2) := by
        rw [Finset.sum_const, nsmul_eq_mul]
    _ = 2 ^ B.card * (2 : ℝ) ^ ((A.card : ℝ) / 2) := by
        rw [Finset.card_powerset]
        push_cast
        ring

/-- **Conditional bound at the BLST scale.**  With `A ⊆ {1,…,n}` sum-free,
`|A| ≤ (n+1)/2`, so under `SumFreeMISBound A B` the container
`A ∪ B` houses at most `2^{|B|} · 2^{(n+1)/4}` maximal sum-free sets — the
`1/4` exponent plus the `|B|` defect. -/
theorem card_maxSumFreeSets_filter_union_le_two_pow_quarter {n : ℕ}
    {A B : Finset ℤ}
    (hAI : A ⊆ interval n) (hAsf : IsSumFree A)
    (hDet : SumFreeMISBound A B) :
    (((maxSumFreeSets n).filter (· ⊆ A ∪ B)).card : ℝ) ≤
      2 ^ B.card * (2 : ℝ) ^ (((n : ℝ) + 1) / 4) := by
  refine (card_maxSumFreeSets_filter_union_le_two_pow_mul_two_rpow hAI hAsf
    hDet).trans ?_
  refine mul_le_mul_of_nonneg_left ?_ (pow_nonneg (by norm_num) _)
  refine Real.rpow_le_rpow_of_exponent_le (by norm_num : (1 : ℝ) ≤ 2) ?_
  have hcard : 2 * A.card ≤ n + 1 := two_mul_card_le_of_isSumFree hAI hAsf
  have h2 : (A.card : ℝ) ≤ ((n : ℝ) + 1) / 2 := by
    have h3 : (2 * A.card : ℝ) ≤ (n : ℝ) + 1 := by exact_mod_cast hcard
    linarith
  linarith

end JSP000728
